apiVersion: apps/v1
kind: Deployment
metadata:
  name: monigan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monigan-api
  template:
    metadata:
      labels:
        app: monigan-api
    spec:
      containers:
        - name: monigan-api
        # This image is going to be the path to the image you create in a future step
          image: us-docker.pkg.dev/my-devops-team-404512/monigan-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "250m"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
